version: '3'
services:
  todotests:
    image: todotests
    #restart: always
    depends_on:
      - todofront
      - todoback
    environment:
      - FRONT_HOST=todofront
  todofront:
    image: todofrontend
    ports:
      - "3000:3000"
    #restart: always
    environment:
      - REACT_APP_API_HOST=todoback
    depends_on:
      - todoback
  todoback:
    image: todobackend
    ports:
      - "3001:3001"